FROM ubuntu:16.04

RUN apt-get update
RUN apt-get install -y git

RUN mkdir /app
WORKDIR /app

RUN git clone https://github.com/feeleep75/nheqminer.git && cd nheqminer
RUN apt-get install -y qt5-default
RUN apt-get install make
RUN apt-get install build-essential g++ -y
RUN apt-get install cmake build-essential libboost-all-dev -y

RUN cd nheqminer/nheqminer && mkdir build
WORKDIR /app/nheqminer/nheqminer/build

RUN cmake ..
RUN make

#RUN qmake ../nheqminer/nheqminer.pro
